### ISSUE TITLE
Compatibility issue with webdriver remote

### ISSUE THREAD

**Issue by dalvarezdc** [diprajpatra/selenium-stealth#22]
Hello guys, I am trying to use stealth with Chromedriver remote, and I think it's having compatibility issues with Selenium-Stealth, is there any way I can integrate selenium stealth with chromedriver?

`Traceback (most recent call last):
  File "/code/bot/project/management/commands/launch_account_in_browser.py", line 29, in handle
    scraper.init_driver()
  File "/code/bot/project/scraper/project.py", line 83, in wrapped
    return func(*args, **kwargs)
  File "/code/bot/project/scraper/project.py", line 533, in init_driver
    fix_hairline=True,
  File "/usr/local/lib/python3.7/site-packages/selenium_stealth/__init__.py", line 41, in stealth
    raise ValueError("driver must is selenium.webdriver.Chrome, currently this lib only support Chrome")
ValueError: driver must is selenium.webdriver.Chrome, currently this lib only support Chrome
`

**Comment by Alfiec7113** [comment]
Did you get anywhere with this?
Just wondering as I wanted to do the same

**Comment by Wamy-Dev** [comment]
I also cannot use it remotely. Same with selenium undetected.
